; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-8048S050C]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32-8048S050C
framework = arduino
board_build.filesystem = none

build_flags =
    -DESP32_8048S050C
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_48=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC=1
    -DST7262_PANEL_CONFIG_TIMINGS_PCLK_HZ=(12000000)
    

lib_deps =
    https://github.com/rzeldent/esp32-smartdisplay.git
    lvgl/lvgl @ ^9.2.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0