; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-8048S070C]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32-8048S070C
framework = arduino
board_build.filesystem = none
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.f_flash = 80000000L

build_flags =
    -DESP32_8048S070C
    -DESP32_SMARTDISPLAY_LCD_RGB_BOUNCE_BUFFER_SIZE=(800*40)
    -DESP32_SMARTDISPLAY_LCD_RGB_DOUBLE_BUFFER=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_48=1
    -DST7262_PANEL_CONFIG_TIMINGS_PCLK_HZ=(15500000)
    -DBOARD_HAS_PSRAM
    

lib_deps =
    https://github.com/rzeldent/esp32-smartdisplay.git
    lvgl/lvgl @ ^9.2.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0